// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using _808Music.Infrastructure.Persistence;

#nullable disable

namespace _808Music.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MusicDbContext))]
    [Migration("20260705172000_AddTrackAudioAnalysis")]
    partial class AddTrackAudioAnalysis
    {
    }
}
